export   { default as   PostVideo } from "./PostVideo"
export   { default as   PostImg } from "./PostImg"
export   { default as   PostText } from "./PostText"
export   { default as   PostMultiImg } from "./PostMultiImg"
export   { default as   Post } from "./Post"